# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2016-11-21 16:45
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recording',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Public ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('audio_file', models.FileField(blank=True, null=True, upload_to='audio_files', verbose_name='Audio file')),
                ('in_progress', models.BooleanField(default=False, verbose_name='Recoridng in progress')),
                ('s3_path', models.CharField(blank=True, max_length=255, null=True, verbose_name='S3 path')),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
    ]
