# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2016-11-23 04:43
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('booth', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Public ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('date', models.DateTimeField(blank=True, null=True, verbose_name='Date')),
                ('rule', models.CharField(blank=True, max_length=255, null=True, verbose_name='Recurring rule')),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
    ]
