# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2016-11-25 00:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booth', '0002_schedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Active'),
        ),
    ]
