# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2016-11-25 01:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booth', '0003_schedule_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='duration',
            field=models.IntegerField(default=30, verbose_name='Duration (minutes)'),
        ),
    ]
