# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2016-11-25 01:50
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booth', '0005_auto_20161124_2044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='time',
            field=models.TimeField(default=datetime.time(1, 50, 31, 856605), verbose_name='Time to record'),
            preserve_default=False,
        ),
    ]
