# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2016-11-25 13:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booth', '0006_auto_20161124_2050'),
    ]

    operations = [
        migrations.AddField(
            model_name='recording',
            name='schedule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='booth.Schedule'),
        ),
    ]
