# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2016-11-26 01:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booth', '0007_recording_schedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='crontab',
            field=models.CharField(blank=True, help_text='A crontab format for recurring schedules', max_length=255, null=True, verbose_name='Crontab format'),
        ),
    ]
