# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2016-11-26 01:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booth', '0008_schedule_crontab'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='rule',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='time',
        ),
    ]
