# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2016-11-26 02:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booth', '0009_auto_20161125_2038'),
    ]

    operations = [
        migrations.AddField(
            model_name='recording',
            name='finished',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Finished'),
        ),
        migrations.AlterField(
            model_name='recording',
            name='in_progress',
            field=models.BooleanField(default=True, verbose_name='Recoridng in progress'),
        ),
    ]
