# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2016-12-05 17:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booth', '0010_auto_20161125_2148'),
    ]

    operations = [
        migrations.AddField(
            model_name='recording',
            name='duration',
            field=models.IntegerField(blank=True, null=True, verbose_name='Duration (minutes)'),
        ),
        migrations.AlterField(
            model_name='recording',
            name='finished',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Finished'),
        ),
    ]
